name: vite lint

on:
  pull_request:
    paths:
      - client/**
      - .github/workflows/vite-lint.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npm i -g pnpm
      - working-directory: ./client
        run: pnpm i --frozen-lockfile
      - working-directory: ./client
        run: pnpm run lint